added dependencies and checkstyle flow
citruscaviar/online-book-store pull request #2
Opened 2024-09-03 14:48 UTC by citruscaviar

2024-09-04 10:51 UTC, okuzan requested changes

2024-09-04 10:51 UTC, okuzan commented on src/main/java/com/onlinebookstore/store/service/BookServiceImpl.java
> +    }
add implementation

2024-09-04 10:51 UTC, okuzan commented on src/main/java/com/onlinebookstore/store/repository/BookRepositoryImpl.java
> +    }
add impl

2024-09-04 10:51 UTC, okuzan commented on src/main/java/com/onlinebookstore/store/model/Book.java
> +@Data
DOn't use Data from Lombok on JPA entities, it can cause problems, you can read more about it. use simple Getter and Setter for now

2024-09-04 10:51 UTC, okuzan commented on checkstyle.xml
> +</module>
```suggestion
</module>

```

2024-09-04 10:52 UTC, okuzan commented on src/main/java/com/onlinebookstore/store/model/Book.java
> +    @Column(nullable = false,unique = true)
```suggestion
    @Column(nullable = false, unique = true)
```
don't forget to Ctrl Alt L autoformat

2024-09-04 10:52 UTC, okuzan commented on src/main/java/com/onlinebookstore/store/repository/BookRepository.java
> +
```suggestion
```

2024-09-05 14:03 UTC, Elena-Bruyako requested changes
see comments

2024-09-05 14:03 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/repository/BookRepositoryImpl.java
> +    private final SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
Don't need to use HibernateUtil
```suggestion
    private final SessionFactory sessionFactory;
```

2024-09-05 14:03 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/repository/BookRepositoryImpl.java
> +public class BookRepositoryImpl implements BookRepository {
```suggestion
@Repository
@RequiredArgsConstructor
public class BookRepositoryImpl implements BookRepository {
```

2024-09-05 14:03 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Cannot add a book to the database", e);
```suggestion
            throw new DataProcessingException("Cannot add a book to the database", e);
```

2024-09-05 14:03 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Failed to find all Books", e);
```suggestion
            throw new DataProcessingException("Failed to find all Books", e);
```

2024-09-05 14:03 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/service/BookServiceImpl.java
> +public class BookServiceImpl implements BookService {
```suggestion
@Service
@RequiredArgsConstructor
public class BookServiceImpl implements BookService {
```

2024-09-05 14:03 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/service/BookServiceImpl.java
> +    }
```suggestion
```

2024-09-05 14:03 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/util/HibernateUtil.java
> +public class HibernateUtil {
remove

2024-09-05 14:03 UTC, Elena-Bruyako commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
add application.properties to src/main/resources and provide spring.datasource properties to connect to the DB 
Also, don't forget 
```
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
```

2024-09-05 16:12 UTC, Elena-Bruyako requested changes
see comments

2024-09-05 16:12 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/StoreApplication.java
> +            bookRepository.save(book);
See comment above 

you need to create CommandLineRunner bean and **call all methods from BookService**

2024-09-05 16:12 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/repository/BookRepository.java
> +
remove empty line

2024-09-05 16:12 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/repository/BookRepositoryImpl.java
> +    @Autowired
```suggestion
```

2024-09-05 16:12 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Cannot add a book to the database", e);
fix comment

2024-09-05 16:12 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Failed to find all Books", e);
fix comment

2024-09-05 16:12 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/service/BookServiceImpl.java
> +    @Autowired
```suggestion
```

2024-09-05 16:12 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/util/HibernateUtil.java
> +public class HibernateUtil {
remove class

2024-09-05 19:50 UTC, sarakhmen approved these changes

2024-09-12 11:30 UTC, merged