Homework 3
citruscaviar/online-book-store pull request #4
Opened 2024-09-26 14:52 UTC by citruscaviar

2024-09-27 07:26 UTC, liliia-ponomarenko requested changes
Good job! Let's improve your solution ;)

2024-09-27 07:26 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/store/repository/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book,Long> {
```suggestion
public interface BookRepository extends JpaRepository<Book, Long> {
```

2024-09-27 07:26 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/store/service/BookServiceImpl.java
> +        book.setCoverImage(requestDto.getCoverImage());
you should use Mapper for this logic.

2024-09-27 07:26 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-fill-books-table.yaml
> +                  value: "https://example.com/cover3.jpg"
each file must end with an empty line (check other files)

2024-09-29 17:04 UTC, Elena-Bruyako requested changes
see comments

2024-09-29 17:04 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: "false"
add empty line at the end of the file

2024-09-29 17:04 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-fill-books-table.yaml
> +      id: fill-books-table
you don't need to save books this way, remove changeset

2024-09-29 17:04 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/02-fill-books-table.yaml
add empty line at the end of the file

2024-09-29 17:04 UTC, Elena-Bruyako commented on src/test/resources/application.properties
> +spring.jackson.deserialization.fail-on-unknown-properties=true
add empty line at the end of the file

2024-10-01 08:11 UTC, liliia-ponomarenko approved these changes
Good job! But please fix my comment before merging ;)

2024-10-01 08:11 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/store/mapper/BookMapper.java
> +    @Mapping(target = "id", ignore = true) // Ignore id when updating
```suggestion
    @Mapping(target = "id", ignore = true) 
```
redundant comment

2024-10-01 08:11 UTC, liliia-ponomarenko commented on src/main/resources/application.properties
> +
```suggestion
```
only one empty line at the end of the file ;)

2024-10-05 12:46 UTC, merged