added GlobalExceptionHandler, custom validation annotations
citruscaviar/online-book-store pull request #5
Opened 2024-10-05 14:30 UTC by citruscaviar

2024-10-06 10:43 UTC, Elena-Bruyako requested changes
see comments

2024-10-06 10:43 UTC, Elena-Bruyako commented on pom.xml
> +			<version>${hibernate-validator.version}</version>
```suggestion
			<groupId>org.springframework.boot</groupId>
                         <artifactId>spring-boot-starter-validation</artifactId>
```

2024-10-06 10:43 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/dto/CreateBookRequestDto.java
> +    @Description
```suggestion
    @Size
```

don't need to create custom annotation to validate size

2024-10-06 10:43 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/validation/DescriptionValidator.java
> +public class DescriptionValidator implements ConstraintValidator<Description, String> {
remove

2024-10-06 10:43 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/validation/Description.java
> +public @interface Description {
remove

2024-10-07 07:53 UTC, liliia-ponomarenko approved these changes
Awesome 😎

2024-10-08 13:46 UTC, merged