implemented support for JWT, added login endpoint
citruscaviar/online-book-store pull request #9
Opened 2024-10-23 17:28 UTC by citruscaviar

2024-10-23 17:40 UTC, Elena-Bruyako requested changes
see comments

2024-10-23 17:40 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/config/SecurityConfig.java
> +                    .requestMatchers("/auth/registration", "/auth/login",
```suggestion
                    .requestMatchers("/auth/**",
```

2024-10-23 17:40 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-10-23 17:40 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
create constant for `TOKEN_HEADER = "Bearer "`

2024-10-23 17:40 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/store/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(TOKEN_HEADER.length());
```

2024-10-23 17:40 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/05-create-users_roles-table.yml
> +            tableName: users_roles
```suggestion
```

2024-10-24 06:09 UTC, liliia-ponomarenko approved these changes
Awesome 😎

2024-10-26 07:52 UTC, merged